#!/bin/bash
#
# This script monitors changes to a markdown file, converts it to HTML 
# using Pandoc, and updates the output HTML file.
#
# Dependencies:
# - https://github.com/jgm/pandoc
# - https://github.com/emcrisostomo/fswatch
#
# Author: https://github.com/srciaga
# Last revised: May 28, 2024
#

# Check if dependencies are installed
check_cmd_installed() {
  if ! command -v "$1" &> /dev/null; then
    echo "Error: $1 is not installed. Please install $1 before running this script."
    exit 1
  fi
}

check_cmd_installed "fswatch"
check_cmd_installed "pandoc"

# Check if files exist
TEMPLATE="./template/template.html"
WATCH="./template/guide.md"
OUTPUT="./site/index.html"

check_file_exists() {
  if [ ! -f "$1" ]; then
    echo "Error: $1 does not exist."
    exit 1
  fi
}

check_file_exists "$TEMPLATE"
check_file_exists "$WATCH"
check_file_exists "$OUTPUT"

# Watch for updates
fswatch --event "Updated" -v "$WATCH" | while read -r; do 
  pandoc --standalone --template "$TEMPLATE" "$WATCH" -o "$OUTPUT"
done
